##### options #####
set -g mouse on
set -g history-limit 100000
setw -g mode-keys vi
set -g status-keys vi
set -g focus-events on
set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1
set -g escape-time 10
set -g set-clipboard on
set -g xterm-keys on
set -g allow-rename off
