format = """
$username$hostname :: $directory$all\
$line_break\
$character"""

[username]
show_always = true
format = "[$user](bold blue)"

[hostname]
ssh_only = false
format = "[@$hostname](bold blue)"

[directory]
format = "[$path](bold cyan)[$read_only](red) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
