# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Monitor Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Monitor wiki https://wiki.hyprland.org/Configuring/Monitors/

# monitor = , preferred, auto, 1
monitor = HDMI-A-1, 2560x1440@60, 0x0, 1
monitor = DP-1, 3840x2160@60, 2560x0, 1
# monitor = HDMI-A-2, 1920x1080@60, 6400x0, 1, transform, 1  # Third monitor disconnected

# If you need to scale things like steam etc, please uncomment these lines.
#xwayland {
#  force_zero_scaling = true       # Unscale XWayland
#}

# Adjust GDK_SCALE accordingly to your liking.
#env = GDK_SCALE, 1.25                   # GDK Scaling Factor
